### ISSUE TITLE
Translate File Field

### ISSUE THREAD

**Issue by kickdev** [kongulov/nova-tab-translatable#10]
A similar issue with this https://github.com/spatie/nova-translatable/issues/18
/trix-attachment/translations_content_en
Uncaught (in promise) ReferenceError: __ is not defined
/trix-attachment/translations_content_en/9060d4cb-7b15-48d8-9a2f-32b9b5f7a06c 404 (Not Found)
The story is the same with other types of editors.

**Comment by kongulov** [comment]
@kickdev I tried to find a solution for him, but it didn't work. Since the trix filesystem keeps its files in a different field, this causes a problem. Compatibility with the trix file system will not work.

**Comment by kickdev** [comment]
But the same will happen with froala. https://github.com/froala/nova-froala-field/issues/26.
Taking the package `optimistdigital/nova-translatable`
I used the [route binding](https://laravel.com/docs/8.x/routing#route-model-binding) option. And thus it works as it should
`Route::bind('field', function ($field) {
            if (
                Str::of($field)->endsWith('.en') ||
                Str::of($field)->endsWith('.ru')
            ) {

                $column = Str::of($field)->replaceLast('.' . Str::of($field)->explode('.')->last(), '')->__toString();

                if ($column === 'content') {
                    if (Route::currentRouteAction() === 'Froala\\NovaFroalaField\\Http\\Controllers\\FroalaUploadController@destroyPending') {
                        (new \Froala\NovaFroalaField\Models\PendingAttachment)->persistDraft(
                            request('draftId'),
                            \Froala\NovaFroalaField\Froala::make($column)->withFiles('public'),
                            \App\Models\News::where('content', $column)->first()
                        );
                    }

                    return $column;
                }

                return $field;
            }

            return $field;
        });`
Maybe it makes sense to add an additional field with the ability to bind? In addition, we can get a model from a resource, but at the same time have an additional option for this?

**Comment by kickdev** [comment]
I've been thinking a little, why shouldn't the package itself interfere with the work of the Trix/Froala system. Froala itself inherits all the basic elements from Trix. What is the idea to create your own element that inherits from Trix and override the function that is responsible for the fields, i.e. `fillAttribute`. Thus, after collecting the fields, we will get a working nesting system

**Comment by kongulov** [comment]
@kickdev https://github.com/kongulov/nova-tab-translatable/issues/14#issuecomment-951816480

Update and see does this solves your problem? I wrote the code to make it work with the native file.

If this does not help, then I will rewrite it to support trix

**Comment by kickdev** [comment]
@kongulov 
> Update and see does this solves your problem? I wrote the code to make it work with the native file.
Unfortunately, it didn’t help.
But I'm using froala, which inherits the interface from Trix.
