### ISSUE TITLE
Default Image::make not working

### ISSUE THREAD

**Issue by orchie** [kongulov/nova-tab-translatable#14]
when I tried save, it throw an exception like title.
the config file tab-translatable.php is default .
'source' => 'array'

please help~ thanks~

**Comment by kongulov** [comment]
@orchie You either did not install the package `spatie/laravel-translatable` or did not configure the model

**Comment by orchie** [comment]
> package

thanks~ this ok. I forgot use Spatie\Translatable\HasTranslations in my Model

and other problems:
```
NovaTabTranslatable::make([
                Image::make('Img','img'),
                Text::make("Url", 'url')->default("aa"),
            ]),
```
the default is invalid, if the value is not required and not input 
the data [url] in database is like this
```
{"hk": null}
```
will drop other langs.

and i test img field,upload two langs , but only one saved.
data [img] like this
```
{"en": "UJnTiXQFF6AGWshQUVw8Y8BU0yRv8kpXHM2ug8Z3.jpg"}
```
thanks~

**Comment by orchie** [comment]
@kongulov hi, the field "Image"  has bugs...  like this

> > package
> 
> thanks~ this ok. I forgot use Spatie\Translatable\HasTranslations in my Model
> 
> and other problems:
> 
> ```
> NovaTabTranslatable::make([
>                 Image::make('Img','img'),
>                 Text::make("Url", 'url')->default("aa"),
>             ]),
> ```
> 
> the default is invalid, if the value is not required and not input
> the data [url] in database is like this
> 
> ```
> {"hk": null}
> ```
> 
> will drop other langs.
> 
> and i test img field,upload two langs , but only one saved.
> data [img] like this
> 
> ```
> {"en": "UJnTiXQFF6AGWshQUVw8Y8BU0yRv8kpXHM2ug8Z3.jpg"}
> ```
> 
> thanks~

**Comment by kongulov** [comment]
@orchie I have corrected the default value. I am looking for image solutions

**Comment by kongulov** [comment]
@orchie After checking, say whether everything is ok or not
