### ISSUE TITLE
Nova 4

### ISSUE THREAD

**Issue by kamrangaravaliyev** [kongulov/nova-tab-translatable#15]
Hello. The package does not support Nova 4

**Comment by aghayeff** [comment]
> Hello. The package does not support Nova 4

PR is welcome :)

**Comment by kongulov** [comment]
@kamrangaravaliyev In progress

**Comment by kongulov** [comment]
@kamrangaravaliyev Please update the package to the 2.0.0 version

https://github.com/kongulov/nova-tab-translatable/releases/tag/2.0.0

**Comment by kamrangaravaliyev** [comment]
thanks
