### ISSUE TITLE
Nova4 + Laravel9

### ISSUE THREAD

**Issue by olivM** [kongulov/nova-tab-translatable#17]
Hi,

i can't find a way to install the package on a L9+nova4 instance

v2.0 require spatie/laravel-translatable ^4.0
but suppport of L9 was added in [5.2.0](https://github.com/spatie/laravel-translatable/releases/tag/5.2.0)

**Comment by kongulov** [comment]
Hi @olivM 

Thank you very much for contacting
Please use version 2.0.2

**Comment by olivM** [comment]
wonderful !
thanks
