### ISSUE TITLE
External package

### ISSUE THREAD

**Issue by kamrangaravaliyev** [kongulov/nova-tab-translatable#20]
Hi, I tried to use it with SimpleRepeatable. i am getting error.
Kongulov\NovaTabTranslatable\NovaTabTranslatable::Kongulov\NovaTabTranslatable\{closure}(): Argument #2 ($model) must be of type Illuminate\Database\Eloquent\Model, null given {"userId":1,"exception":" [object] (TypeError(code: 0): Kongulov\\NovaTabTranslatable\\NovaTabTranslatable::Kongulov\\NovaTabTranslatable\\{closure}(): Argument #2 ($model) must be of type Illuminate\\Database\\Eloquent \\Model, null given at /var/www/vendor/kongulov/nova-tab-translatable/src/NovaTabTranslatable.php:118)

**Comment by kongulov** [comment]
@kamrangaravaliyev Hi,

What is your nova version?

**Comment by kamrangaravaliyev** [comment]
Nova version 3

**Comment by kongulov** [comment]
@kamrangaravaliyev May I know what version of the package you have installed?

**Comment by kamrangaravaliyev** [comment]
yes.
Laravel Nova version. 3.32.0
"outl1ne/nova-simple-repeatable": "1.4.3",
"kongulov/nova-tab-translatable": "^1.1",

**Comment by kamrangaravaliyev** [comment]
SimpleRepeatable::make('Days', 'days', [
                        NovaTabTranslatable::make([
                            Text::make("Name", 'name')->rules('required_lang:az'),
                            Trix::make("Description")->rules('required_lang:az')
                        ]),
                    ])->addRowLabel("Gün əlavə et")

This is the code. Unfortunately it doesn't work

**Comment by kongulov** [comment]
@kamrangaravaliyev 

The "NovaTabTranslatable" package works together with the "spatie/laravel-translatable" package where you must specify the "name" field in the model with the translatable $translatable=['name'];
But such a structure will not work with the "SimpleRepeatable" package, so wrapping the "NovaTabTranslatable" package in "SimpleRepeatable" will not work.

But if you wrap "SimpleRepeatable" in "NovaTabTranslatable" then everything will work

```php
NovaTabTranslatable::make([
    SimpleRepeatable::make('Name', 'name', [
        Text::make('Name1'),
        Text::make('Name2'),
    ])
    ->canAddRows(true) // Optional, true by default
    ->canDeleteRows(true), // Optional, true by default
])
```
