### ISSUE TITLE
Red asterix next to "AT" 

### ISSUE THREAD

**Issue by mgralikowski** [kongulov/nova-tab-translatable#24]
I discovered a very strange issue.

```php
'locales' => [
    'en', 'at', 'pl',
],
```

```php
NovaTabTranslatable::make([
    Text::make('title')->sortable(),
])->setTitle('Translations'),
```

A result:
![image](https://user-images.githubusercontent.com/17027876/195193225-5ad56195-aaab-43ac-86f5-03c741fbbb86.png)

As you can see, even though I haven't marked any field as required, the "at" language has a red asterisk. What is funny this issue is strictly related to the `at` language code, only when is written in lowercase. Adding even a space or changing to `aT` fixing this issue. 

There is no difference if DB or array source is used.

**Comment by kongulov** [comment]
@mgralikowski 

Thank you very much for finding the problem!
Problem solved, please update the package to the new version
