### ISSUE TITLE
Package overrides some of default nova routes

### ISSUE THREAD

**Issue by aghayeff** [kongulov/nova-tab-translatable#26]
Hi,
Nova Version: 4.16.1
Laravel Version: 9
Php 8.0

after installing tab-translatable package, I came across that File Deletion does not work, return 404 error. I checked all routes using the command

`php artisan route:list`

and saw that your package overrides default some Nova routes. Take a look to the screenshot, especially the first, second and the last routes

<img width="1204" alt="Screen Shot 2022-10-21 at 14 30 52" src="https://user-images.githubusercontent.com/7493431/197176399-bf3342f1-2431-409d-b730-a72e3623e08e.png">

**Comment by kongulov** [comment]
@aghayeff 

Thank you very much for finding the problem!
Problem solved (https://github.com/kongulov/nova-tab-translatable/commit/b5face5f17092911bdf86523c72cc612ff1ff64a), please update the package to the new version (2.0.7)
