### ISSUE TITLE
TranslatableTabToRowTrait does not take an effect in Nova 4.16

### ISSUE THREAD

**Issue by aghayeff** [kongulov/nova-tab-translatable#27]
Hi, `TranslatableTabToRowTrait` in resource does not take an effect.

Nova version: 4.16
Laravel version: 9
Php: 8.0

**Comment by mgralikowski** [comment]
Nova: 4.18 the issue still occurs.
In my case, it is more critical. We use tabs ([eminiarts/nova-tabs](https://github.com/eminiarts/nova-tabs)) and "translatable tabs" on index pages can't display any content:
![image](https://user-images.githubusercontent.com/17027876/202200127-abeb9a9c-c5d2-465b-9af4-ad27c29be53c.png)
It was the case also for the previous version, but a simple solution was using this trait.

@kongulov could You take a look?

**Comment by kongulov** [comment]
@aghayeff, @mgralikowski 

Thank you very much for finding the problem!
Problem solved, please update the package to the new version (2.0.9)
