### ISSUE TITLE
Add support for required_with rule

### ISSUE THREAD

**Issue by bcoelhodev** [kongulov/nova-tab-translatable#29]
Hi,

`required_with` rule is not working inside of `NovaTabTranslatable`. Is it possible to fix?

Example:
```
NovaTabTranslatable::make([
    Text::make('Link label Button', 'link_label')
        ->rules('required_with:link_url', 'max:255', 'nullable'),
    Text::make('Link url Button', 'link_url')
        ->rules('required_with:link_label', 'max:255', 'nullable'),
])
```

PHP 8.1.12
Laravel 9.40.1
Nova 4.19.2

**Comment by kongulov** [comment]
@bcoelhodev 

Thank you very much for finding the problem!
Problem solved, please update the package to the new version (2.0.11)
