### ISSUE TITLE
The content of Trix editor is not working properly

### ISSUE THREAD

**Issue by aimalamiri** [kongulov/nova-tab-translatable#3]
I think the php functin `htmlspecialchars()` adding automatically in the details page.
![SharedScreenshot](https://user-images.githubusercontent.com/34779928/94614157-f86d0900-02ba-11eb-8fdc-a7c21886a761.jpg)

**Comment by kongulov** [comment]
@aimalamiri Thanks for your vigilance.
I added v-html there, now html will be displayed correctly there.

https://github.com/kongulov/nova-tab-translatable/commit/c5f98142365b85de997de75a86400e510e89468f
