### ISSUE TITLE
Package does not work with nova filemanager

### ISSUE THREAD

**Issue by TEstDevelo** [kongulov/nova-tab-translatable#34]
Hello. This package is not work with field nova-file-manager: https://novapackages.com/packages/oneduo/nova-file-manager. I get errors: https://imgur.com/a/1dHynwW . We can fix it?

Laravel Nova: 4.0
Nova File Manager: v0.8.3

In model I have get attributes for translation (link on documentation: https://oneduo.github.io/nova-file-manager/installation.html), we need set casts for file fields:

    public function getFileAttribute($value): ?AssetObject
    {
        if ($value) {
            return new AssetObject('public', $value);
        }

        return null;
    }

    public function getMobileFileAttribute($value): ?AssetObject
    {
        if ($value) {
            return new AssetObject('public', $value);
        }

        return null;
    }

**Comment by kongulov** [comment]
@TEstDevelo This problem is on the side of that package, as it overrides the default save to the database.
