### ISSUE TITLE
The "help" text does not render

### ISSUE THREAD

**Issue by mgralikowskifrontkom** [kongulov/nova-tab-translatable#36]
Hi,

this function: https://nova.laravel.com/docs/resources/fields.html#field-help-text doesn't work when tabs are used. I don't see any change in the result HTML when the `help()` method is used. Moving the field outside translatable tabs makes it work.

**Comment by kongulov** [comment]
Hi @mgralikowskifrontkom 

Can you please describe the problem in more detail?
Can you send a sample code? for me to reproduce the error

**Comment by mgralikowskifrontkom** [comment]
Here you are:

`Text::make('Foo')->help('Display me please');`

**Comment by kongulov** [comment]
@mgralikowskifrontkom 

And please write which version of nova and packages you are using

**Comment by mgralikowskifrontkom** [comment]
I tried the most recent version.
