### ISSUE TITLE
Нет совместимости с KeyValue

### ISSUE THREAD

**Issue by Galifax** [kongulov/nova-tab-translatable#8]
Сам перевод сохраняется в поле нормально, но при редактировании разбивает каждый символ на ключ и значение

**Comment by kongulov** [comment]
Здравствуйте.

Спасибо большое за найденную проблему.

Проблема Устранена.
Можете обновить версию плагина до [1.0.11](https://github.com/kongulov/nova-tab-translatable/releases/tag/1.0.11)
