### ISSUE TITLE
Translatable fields cannot be inside a Panel if TranslatableTabToRawTrait is used.

### ISSUE THREAD

**Issue by miagg** [kongulov/nova-tab-translatable#9]
Hi,
It seems that Panels do not work well with this package.

See the image bellow. If I use `TranslatableTabToRowTrait`, the fields pop-out of the panel.

```
Panel::make('Photo Details', [
    ID::make()->sortable()->hide(),
   
    // ... some fields
   
   NovaTabTranslatable::make([
        Textarea::make('Description')
            ->placeholder('Optional Description')
            ->rows(2)
            ->sortable()
    ]),
])->withToolbar(),
```
Is there a quick fix for this?
![Screenshot 2021-06-12 at 12 47 37 PM](https://user-images.githubusercontent.com/6439071/121772466-2448ca00-cb7e-11eb-9b01-c7abfcac2647.png)

**Comment by kongulov** [comment]
@miagg Can you tell "Panel" which package is it?

**Comment by miagg** [comment]
> @miagg Can you tell "Panel" which package is it?

I'm talking about native [field Panels](https://nova.laravel.com/docs/3.0/resources/fields.html#field-panels).

**Comment by kongulov** [comment]
@miagg 
Done. Take the new version and check please
https://github.com/kongulov/nova-tab-translatable/commit/0ef0bfc6a18bbda9801713afe0c89562198f89db

**Comment by miagg** [comment]
> @miagg
> Done. Take the new version and check please.
> 1.0.13 : [0ef0bfc](https://github.com/kongulov/nova-tab-translatable/commit/0ef0bfc6a18bbda9801713afe0c89562198f89db)

Yes! It's working perfectly now. Thanks for the quick fix!
